//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int OrderID { get; set; }
        public Nullable<decimal> CostOrder { get; set; }
        public Nullable<int> SumDiscount { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
        public Nullable<int> PointIssueIds { get; set; }
        public Nullable<int> StatusIds { get; set; }
    
        public virtual PointIssue PointIssue { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
