//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public int ProductIds { get; set; }
        public int OrderIds { get; set; }
        public Nullable<int> CountProductOrder { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
